--liquibase formatted sql

--changeset AndresGarcia:1

--comment: Crear tabla principal de paquetes con soporte para JSONB, tabla de historial de ubicaciones, tabla de historial de estados

CREATE TABLE packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id VARCHAR(50) NOT NULL,
    delivery_address JSONB NOT NULL,
    dimensions JSONB NOT NULL,
    CONSTRAINT uk_packages_tracking_id UNIQUE (tracking_id)
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100),
    country VARCHAR(100),
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    package_id BIGINT NOT NULL,
    CONSTRAINT fk_locations_package_id FOREIGN KEY (package_id) REFERENCES packages(id)
);

CREATE TABLE status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    package_id BIGINT NOT NULL,
    CONSTRAINT fk_status_history_package_id FOREIGN KEY (package_id) REFERENCES packages(id)
);

CREATE INDEX idx_locations_package_id ON locations(package_id);
CREATE INDEX idx_status_history_package_id ON status_history(package_id);